routes/web.php
<?php

use App\Category;
use App\Destination;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index');
});

Route::resource('accounts', 'AccountsController');


Auth::routes();

//Route::resource('admin_tour', 'TourController')->middleware('ad');

Route::post('searchDes','DestinationController@search')->name('searchDes');
Route::post('searchTour','TourController@search')->name('searchTour');
Route::resource('category', 'CategoryController');
Route::post('ckeditor/image_upload',
    'CKEditorController@upload')->name('upload');
Route::get('/home',function (){
        return redirect('index');
    }
);
//Route::get('/admin', 'AccountsController@index')->name('admin')->middleware('ad');



Route::get('/index', 'HomeController@index')->name('index');
Route::resource('/tour', 'FrontTourController');
Route::get('/des','HomeController@listDestination')->name('des');
Route::get('/blog',function (){
    return view('blog');
})->name('blog');
Route::get('/contact',function (){
    return view('contact');
})->name('contact');
Route::get('/about',function (){
    return view('about');
})->name('about');
Route::get('/service',function (){
    return view('service');
})->name('service');
Route::get('mail/send', 'MailController@send');
Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');



Route::get('/addT',function(){
    $lsDes = Destination::all();
    $lsCat = Category::all();
    return view('admin/tour/add') -> with(['lsDes' => $lsDes, 'lsCat' => $lsCat]);
});
Route::post('/addT','Tourcontroller@save')->name('addT');



Route::group(['middleware'=>'auth'],function (){
    Route::get('/info/{id}', 'HomeController@userInfo')->name('info');
    Route::post('/booktour/accept','BooktourController@booked');
    Route::get('/booktour/{id}','BookTourController@showData')->name('booktour');
    Route::post('/payment/{id}/{time}','BookTourController@create');
    Route::get('/return-vnpay/{id}/{time}','BookTourController@return');
});
Route::group(['middleware'=>'ad'],function(){
    Route::resource('destination', 'DestinationController');
    Route::post('/update-des/{id}','DestinationController@update')->name('destination.update');
    Route::get('/destination_detail/{id}','HomeController@detailDes')->name('destination_detail');
    Route::resource('admin_tour', 'TourController');
    Route::get('/admin', 'AccountsController@index')->name('admin');
    Route::get('delete/{id}','AccountsController@destroy')->name('delete');
    Route::get('active/{id}','AccountsController@active')->name('active');
    Route::get('/searchUser','AccountsController@search')->name('search');
});

resources/views/401.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Raleway', sans-serif;
            font-weight: 100;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
            text-align: center;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="title m-b-md flex-center full-height">
    Action unauthorized!
</div>
</body>
</html>

resources/views/about.blade.php
@extends('header')
@section('container')
    <div id="colorlib-about">
        <div class="container">
            <div class="row">
                <div class="about-flex">
                    <div class="col-one-forth aside-stretch animate-box">
                        <div class="row">
                            <div class="col-md-12 about">
                                <h2>About</h2>

                                <ul>
                                    <li><a href="#">History</a></li>
                                    <li><a href="#">Staff</a></li>
                                    <li><a href="#">Connect with us</a></li>
                                    <li><a href="#">Faqs</a></li>
                                    <li><a href="#">Career</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-three-forth animate-box">
                        <h2>History</h2>
                        <div class="row">
                            <div class="col-md-12">
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>

                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>

                                <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>

                                <div class="row row-pb-sm">
                                    <div class="col-md-6">
                                        <img class="img-responsive" src="images/hotel-7.jpg" alt="">
                                    </div>
                                    <div class="col-md-6">
                                        <p>The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.</p>
                                        <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
                                    </div>
                                </div>


                                <p>When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>

                                <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country.</p>

                                <p>But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="colorlib-testimony" class="colorlib-light-grey">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
                    <h2>Our Satisfied Guests says</h2>
                    <p>We love to tell our successful far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 col-md-offset-2 animate-box">
                    <div class="owl-carousel2">
                        <div class="item">
                            <div class="testimony text-center">
                                <span class="img-user" style="background-image: url(images/person1.jpg);"></span>
                                <span class="user">Alysha Myers</span>
                                <small>Miami Florida, USA</small>
                                <blockquote>
                                    <p>" A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                                </blockquote>
                            </div>
                        </div>
                        <div class="item">
                            <div class="testimony text-center">
                                <span class="img-user" style="background-image: url(images/person2.jpg);"></span>
                                <span class="user">James Fisher</span>
                                <small>New York, USA</small>
                                <blockquote>
                                    <p>One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                                </blockquote>
                            </div>
                        </div>
                        <div class="item">
                            <div class="testimony text-center">
                                <span class="img-user" style="background-image: url(images/person3.jpg);"></span>
                                <span class="user">Jacob Webb</span>
                                <small>Athens, Greece</small>
                                <blockquote>
                                    <p>Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
                                </blockquote>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="colorlib-subscribe" style="background-image: url(images/img_bg_2.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
                    <h2>Sign Up for a Newsletter</h2>
                    <p>Sign up for our mailing list to get latest updates and offers.</p>
                    <form class="form-inline qbstp-header-subscribe">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-0">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="email" placeholder="Enter your email">
                                    <button type="submit" class="btn btn-primary">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/bookTour.blade.php
@extends('header')
@section('container')
    <div class="container">
        <form action="{{asset('booktour/accept')}}" enctype="multipart/form-data" class="form" method="post">
            @csrf
            <div class="form-group">
                <label >Tour</label>
                <input type="text" class="form-control" name="tourName" readonly="readonly" value="{{$tour->tour_name}}" >
                <input type="hidden" class="form-control" name="tourId" readonly="readonly" value="{{$tour->id}}">
            </div>
            <div class="form-group">
                <label >Thời gian</label>
                <input type="text" class="form-control" name="tourLength" readonly="readonly" value="{{$tour->num_of_day}} Ngày" >
            </div>
            <div class="form-group">
                <label >Số người (Tối đa :{{$tour->num_of_per}} người)</label>
                <input type="number" class="form-control" name="numPer" placeholder="Enter number of guest" max="{{$tour->num_of_per}}" min="0" required>
            </div>
            <div class="form-group">
                <label >Ngày khởi hành</label>
                <input type="text" class="form-control" name="timeStart" readonly="readonly" value="{{$tour->time_start}} " >
            </div>
            <div class="form-group">
                <label >Price</label>
                <input type="text" class="form-control" name="price" readonly="readonly" value="{{$tour->price}} VND" >
            </div>
{{--            <div class="form-group">--}}
{{--                <label >Số người lớn</label>--}}
{{--                <input type="number" class="form-control" aria-describedby="priceAdult" id="numAdult" placeholder="Số người lớn" >--}}
{{--                <small id="priceAdult" class="form-text text-muted"></small>--}}
{{--            </div>--}}
{{--            <div class="form-group">--}}
{{--                <label >Số trẻ nhỏ</label>--}}
{{--                <input type="number" class="form-control" id="numChild" placeholder="Số trẻ nhỏ" >--}}
{{--            </div>--}}

            <div class="form-group">
                <label >Mã giảm giá</label>
                <input type="text" class="form-control" name="discount" placeholder="Mã giảm giá" >
            </div>
            <button type="submit" class="btn btn-primary">Xác nhận</button>
            <a class="btn btn-danger" href="{{route('admin_tour.show',$tour->id)}}"> Quay lại</a>
        </form>
    </div>

@endsection

resources/views/contact.blade.php
@extends('header')
@section('container')

    <div id="colorlib-contact">
        <div class="container">
            <div class="row">
                <div class="col-md-10 col-md-offset-1 animate-box">
                    <h3>Get In Touch</h3>
                    <form action="#">
                        <div class="row form-group">
                            <div class="col-md-6 padding-bottom">
                                <label for="fname">First Name</label>
                                <input type="text" id="fname" class="form-control" placeholder="Your firstname">
                            </div>
                            <div class="col-md-6">
                                <label for="lname">Last Name</label>
                                <input type="text" id="lname" class="form-control" placeholder="Your lastname">
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <label for="email">Email</label>
                                <input type="text" id="email" class="form-control" placeholder="Your email address">
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <label for="subject">Subject</label>
                                <input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <label for="message">Message</label>
                                <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
                            </div>
                        </div>
                        <div class="form-group text-center">
                            <input type="submit" value="Send Message" class="btn btn-primary">
                        </div>

                    </form>
                </div>
                <div class="col-md-10 col-md-offset-1 animate-box">
                    <h3>Contact Information</h3>
                    <div class="row contact-info-wrap">
                        <div class="col-md-3">
                            <p><span><i class="icon-location"></i></span> 198 West 21th Street, <br> Suite 721 New York NY 10016</p>
                        </div>
                        <div class="col-md-3">
                            <p><span><i class="icon-phone3"></i></span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                        </div>
                        <div class="col-md-3">
                            <p><span><i class="icon-paperplane"></i></span> <a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
                        </div>
                        <div class="col-md-3">
                            <p><span><i class="icon-globe"></i></span> <a href="#">yoursite.com</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="map" class="colorlib-map"></div>

    <div id="colorlib-subscribe" style="background-image: url(images/img_bg_2.jpg);" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
                    <h2>Sign Up for a Newsletter</h2>
                    <p>Sign up for our mailing list to get latest updates and offers.</p>
                    <form class="form-inline qbstp-header-subscribe">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-0">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="email" placeholder="Enter your email">
                                    <button type="submit" class="btn btn-primary">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/success.blade.php
@extends('header')
@section('container')
    <div class="container">
        <h1> {{$msg}} </h1>
        <h2> click vào <a href="{{route('index')}}">link</a> để quay lại trang chính . </h2>
    </div>
    @endsection

resources/views/thong-tin-ca-nhan.blade.php
@extends('header')
@section('container')

		<div class="colorlib-wrap" style="padding-top: 3em;">
        <div class="container">
            <h1 class="text-center">Thông tin cá nhân</h1>
            <div class="container">
            <div class="row profile">
            <div class="col-md-3">
                <div class="profile-sidebar">
                <div class="profile-userpic">
                    <img src="https://hocwebgiare.com/thiet_ke_web_chuan_demo/bootstrap_user_profile/images/profile_user.jpg" class="img-responsive" alt="Thông tin cá nhân">
                </div>
                <div class="profile-usertitle">
                <div class="profile-usertitle-name">                     Họ và Tên: {{$user->full_name}}                </div>
                <div class="profile-usertitle-job">                      Email:{{$user->email}}                   </div>
                </div>
                <div class="profile-userbuttons">
                <button type="button" class="btn btn-success btn-sm">Trang chủ</button>
                <button type="button" class="btn btn-danger btn-sm">Thoát ra</button>
                </div>
                <div class="profile-usermenu">
                <ul class="nav">
                    <!-- <div class="logo_menuchinh" style="float:left; padding-top:5px; padding-left:10px; color:#fff; margin-left:auto; margin-right:auto; text-align=center; line-height:40px; font-size:16px;font-weight:bold;font-family:Arial">HOCWEBGIARE.COM</div><div class="menu-icon"><span>Menu</span></div>                       -->
                <li class="active">                         <a href="https://hocwebgiare.com/">                         <i class="glyphicon glyphicon-info-sign"></i>                           Cập nhật thông tin cá nhân </a>
                </li>
                <li>                            <a href="#">                         <i class="glyphicon glyphicon-heart"></i>                           Tour yêu thích </a>
                </li>
                <li>                            <a href="#" target="_blank">                         <i class="glyphicon glyphicon-shopping-cart"></i>                           Quản lý đơn hàng </a>
                </li>
                <!-- <li>                            <a href="#">                         <i class="glyphicon glyphicon-envelope"></i>                            Tin nhắn </a>
                </li>                    -->
                </ul>
                </div>
                </div>
            </div>
                <div class="col-md-9">
                    <div class="profile-content">             Chào mừng Bạn đến với website Amazing tour </div>
                    <div> Các tour đã book</div>
                    <div class="row">

                    @foreach($tours as $tour)
                        <div class="col-md-6 col-sm-6 animate-box">
                            <div class="tour">
                                <a href="{{route('tour.show', $tour->tour_id)}}" class="tour-img" style="background-image: url(http://res.cloudinary.com/a123abc/image/upload/{{$tour->cover}});">
                                    <p class="price"><span>{{$tour->price}}VNĐ</span> <small>/ người</small></p>
                                </a>
                                <div class="desc">
											<p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
											<h2><a href="{{route('tour.show',$tour->id)}}">{{substr($tour->tour_name, 0, 40)}}...</a></h2>
                                            <span>Khởi hành: {{$tour->time}}</span>
                                                <br>
                                            <span>{{$tour->num_of_per}} người</span>
										</div>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
            </div>
        </div>
		</div>


@endsection

resources/views/tour.blade.php
@extends('header')

@section('container')
    <div class="colorlib-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <div class="row">
                        <div class="wrap-division">
                            @foreach($lsTour as $tour)
                            <div class="col-md-6 col-sm-6 animate-box">
                                <div class="tour">
                                    <a href="{{route('tour.show', $tour->id)}}" class="tour-img" style="background-image: url(http://res.cloudinary.com/a123abc/image/upload/{{$tour->cover}});">
                                        <p class="price"><span>{{$tour->price}}VNĐ</span> <small>/ {{$tour->num_of_day}} Days</small></p>
                                    </a>
                                    <span class="desc">
											<p class="star"><span><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i><i class="icon-star-full"></i></span> 545 Reviews</p>
											<h2><a href="{{route('tour.show', $tour->id)}}">{{substr($tour->tour_name, 0, 40)}}...</a></h2>
											<span class="city">{{$tour->destination->name}}</span>
										</span>
                                </div>
                            </div>
                            @endforeach

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-center">

                            <ul class="pagination">
                                {{ $lsTour->links() }}
                            </ul>
                        </div>
                    </div>
                </div>

                <!-- SIDEBAR-->
                <div class="col-md-3">
                    <div class="sidebar-wrap">
                        <div class="side search-wrap animate-box">
                            <h3 class="sidebar-heading">Find your tour</h3>
                            <form method="post" action="{{route('searchTour')}}" class="colorlib-form">
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="date">Where:</label>
                                            <div class="form-field">
                                                <input type="text" name="tour" class="form-control" placeholder="Search name" value="{{$name}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="date">Guest</label>
                                            <div class="form-field">
                                                <input type="text" name="numPeo" class="form-control" placeholder="Number of guest" value="{{$num}}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <input type="submit" name="submit" id="submit" value="Find Tour" class="btn btn-primary btn-block">
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="side animate-box">
                            <div class="row">
                                <div class="col-md-12">
                                    <h3 class="sidebar-heading">Địa danh khác</h3>
                                    <ul>
                                        <li><a href="">Phú Quốc</a></li>
                                        <li><a href="">Hải Phòng</a></li>
                                        <li><a href="">Lạng Sơn</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="side animate-box">
                            <div class="row">
                                <div class="col-md-12">
                                    <h3 class="sidebar-heading">Tin tức</h3>
                                    <ul>
                                        <li><a href="">Blog 1</a></li>
                                        <li><a href="">Blog 2</a></li>
                                        <li><a href="">Blog 3</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="side animate-box">
                            <div class="row">
                                <div class="col-md-12">
                                    <h3 class="sidebar-heading">Khuyến mãi đặc biệt</h3>
                                    <img src="images/00097-300x600.gif">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div id="colorlib-subscribe" style="background-image: url({{asset('images/img_bg_2.jpg')}});" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center colorlib-heading animate-box">
                    <h2>Sign Up for a Newsletter</h2>
                    <p>Sign up for our mailing list to get latest updates and offers.</p>
                    <form class="form-inline qbstp-header-subscribe">
                        <div class="row">
                            <div class="col-md-12 col-md-offset-0">
                                <div class="form-group">
                                    <input type="text" class="form-control" id="email" placeholder="Enter your email">
                                    <button type="submit" class="btn btn-primary">Subscribe</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection