routes/web.php
<?php

use App\Category;
use App\Destination;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index');
});

Route::resource('accounts', 'AccountsController');


Auth::routes();

//Route::resource('admin_tour', 'TourController')->middleware('ad');

Route::post('searchDes','DestinationController@search')->name('searchDes');
Route::post('searchTour','TourController@search')->name('searchTour');
Route::resource('category', 'CategoryController');
Route::post('ckeditor/image_upload',
    'CKEditorController@upload')->name('upload');
Route::get('/home',function (){
        return redirect('index');
    }
);
//Route::get('/admin', 'AccountsController@index')->name('admin')->middleware('ad');



Route::get('/index', 'HomeController@index')->name('index');
Route::resource('/tour', 'FrontTourController');
Route::get('/des','HomeController@listDestination')->name('des');
Route::get('/blog',function (){
    return view('blog');
})->name('blog');
Route::get('/contact',function (){
    return view('contact');
})->name('contact');
Route::get('/about',function (){
    return view('about');
})->name('about');
Route::get('/service',function (){
    return view('service');
})->name('service');
Route::get('mail/send', 'MailController@send');
Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');



Route::get('/addT',function(){
    $lsDes = Destination::all();
    $lsCat = Category::all();
    return view('admin/tour/add') -> with(['lsDes' => $lsDes, 'lsCat' => $lsCat]);
});
Route::post('/addT','Tourcontroller@save')->name('addT');



Route::group(['middleware'=>'auth'],function (){
    Route::get('/info/{id}', 'HomeController@userInfo')->name('info');
    Route::post('/booktour/accept','BooktourController@booked');
    Route::get('/booktour/{id}','BookTourController@showData')->name('booktour');
    Route::post('/payment/{id}/{time}','BookTourController@create');
    Route::get('/return-vnpay/{id}/{time}','BookTourController@return');
});
Route::group(['middleware'=>'ad'],function(){
    Route::resource('destination', 'DestinationController');
    Route::post('/update-des/{id}','DestinationController@update')->name('destination.update');
    Route::get('/destination_detail/{id}','HomeController@detailDes')->name('destination_detail');
    Route::resource('admin_tour', 'TourController');
    Route::get('/admin', 'AccountsController@index')->name('admin');
    Route::get('delete/{id}','AccountsController@destroy')->name('delete');
    Route::get('active/{id}','AccountsController@active')->name('active');
    Route::get('/searchUser','AccountsController@search')->name('search');
});

app/Destination.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Destination extends Model
{
    use SoftDeletes;
    protected $date = ['deleted_at'];

    public function tours()
    {
        return $this->hasMany('\App\Tour');
    }
    protected $table = 'destinations';
}

app/Http/Controllers/DestinationController.php
<?php

namespace App\Http\Controllers;

use App\Destination;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DestinationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lsDestinations = Destination::all();
        return view('admin/destination/list_des')-> with([
            'lsDestinations' => $lsDestinations
        ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $name = $request->input('name');
        $description=$request->input('description');
        $img=$request->input('imageUrl');
        $destination = new Destination();
        $destination->name = $name;
        $destination->description=$description;
        $destination->image=$img;
        $destination->save();

        $request->session()->flash('success', 'Add destination was successful!');
        return redirect()->route("destination.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $des=Destination::find($id);
        return view('admin/destination/edit')->with(['des'=>$des]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $des=Destination::find($id);
        $des->name=$request->input('name');
        $des->description=$request->input('description');
        $des->image=$request->input('imageUrl');
        $des->save();
        return redirect()->route('destination.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function search(Request $request){
        $name=$request->input('destination');
        $lsDestinations=DB::table('destinations')->where('name','like','%'.$name.'%')
            ->paginate(8);
        return view('destination')-> with([
            'lsDestinations' => $lsDestinations
        ]);
    }
}

resources/views/admin/destination/edit.blade.php
@extends('header')
@section('container')

                <form class="form" method="post"
                      action="{{route('destination.update',$des->id)}}"enctype="multipart/form-data">
                    @csrf

                    <div class="modal-header">
                        <h2 class="modal-title" id="exampleModalLabel">Editdestination</h2>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">destination:</label>
                            <input type="text" class="form-control" name="name" id="recipient-name" value="{{$des->name}}">
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">description:</label>
                            <input type="text" class="form-control" name="description" id="descript" value="{{$des->description}}">
                        </div>
                        <div class="form-group ">
                            <input class="btn btn-outline-info btn-sm" type="file" class="form-control" name="image">
                            <img src="http://res.cloudinary.com/a123abc/image/upload/{{$des->image}}" alt="" id="image-preview" style="width: 100px">
                            <input type="hidden" name="imageUrl" value="{{$des->image}}" >
                        </div>

                    </div>
                    <div class="modal-footer">

                        <button type="submit" class="btn btn-primary update" >Update destination</button>
                    </div>
                </form>

    @endsection

resources/views/admin/destination/list_des.blade.php
@extends('header')

@section('container')
    <div class="container">
        <h2>destination management</h2>
        <!-- <a class="btn btn-primary" href="destination/create">Add</a> -->

        <button type="button" class="btn btn-primary"
                data-toggle="modal" data-target="#exampleModal"
                data-whatever="@mdo">Add</button>

        <p></p>
        <table class="table">
            <tr>
                <th>ID</th>
                <th style="width: 50%">Name</th>
                <th >Update</th>
                <th>Delete</th>
            </tr>

            @foreach($lsDestinations as $des)
                <tr>
                    <td>{{$des->id}}</td>
                    <td>{{$des->name}}</td>
                   <td><a href="destination/{{$des->id}}/edit" class="btn btn-primary">Update</a></td>
                    <td>
                        <form method="POST"
                              action="destination/{{$des->id}}"
                              onsubmit="return confirm('Sure ?')">
                            @csrf
                            @method('DELETE')
                            <input class="btn btn-danger" type="submit" value="Delete" />
                        </form>
                    </td>
                </tr>

            @endforeach
        </table>
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form" method="post"
                      action="{{route('destination.store')}}" enctype="multipart/form-data" >
                    @csrf
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">New destination</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">


                     <div class="form-group">
                         <label for="recipient-name" class="col-form-label">destination:</label>
                         <input type="text" class="form-control" id="recipient-name" name="name">
                     </div>
                     <div class="form-group">
                         <label for="recipient-name" class="col-form-label">description:</label>
                         <input type="text" class="form-control" id="descript" name="description">
                     </div>
                     <div class="form-group ">
                         <input class="btn btn-outline-info btn-sm" type="file" class="form-control" name="image">
                         <img src="" alt="" id="image-preview" style="width: 100px">
                         <input type="hidden" name="imageUrl" id="imageUrl" >
                     </div>



{{--                    <form>--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="recipient-name" class="col-form-label">destination:</label>--}}
{{--                            <input type="text" class="form-control" id="recipient-name">--}}
{{--                        </div>--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="recipient-name" class="col-form-label">description:</label>--}}
{{--                            <input type="text" class="form-control" id="descript">--}}
{{--                        </div>--}}
{{--                        <div class="form-group ">--}}
{{--                            <input class="btn btn-outline-info btn-sm" type="file" class="form-control" name="image">--}}
{{--                            <img src="" alt="" id="image-preview" style="width: 100px">--}}
{{--                            <input type="hidden" name="imageUrl" id="imageUrl" >--}}
{{--                        </div>--}}
{{--                    </form>--}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="senddestination">Add destination</button>
                </div>
                </form>
            </div>

        </div>
    </div>



{{--    <script type="text/javascript">--}}
{{--        $("#senddestination").click(function(e) {--}}
{{--            e.preventDefault();--}}
{{--            var destination = $("#recipient-name").val();--}}
{{--            var descript=$("#descript").val();--}}
{{--            var imageUrl=$("#imageUrl").val();--}}
{{--            var token = "{{csrf_token()}}";--}}
{{--            $.post(--}}
{{--                "{{route('destination.store')}}",--}}
{{--                {name: destination,description:descript, image:imageUrl, _token: token},--}}
{{--                function(result){--}}
{{--                    $('#exampleModal').modal('toggle');--}}
{{--                    $.notify("success", "success");--}}
{{--                    location.reload();--}}
{{--                }--}}
{{--            );--}}
{{--        });--}}
{{--    </script>--}}
@endsection