routes/web.php
<?php

use App\Category;
use App\Destination;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('index');
});

Route::resource('accounts', 'AccountsController');


Auth::routes();

//Route::resource('admin_tour', 'TourController')->middleware('ad');

Route::post('searchDes','DestinationController@search')->name('searchDes');
Route::post('searchTour','TourController@search')->name('searchTour');
Route::resource('category', 'CategoryController');
Route::post('ckeditor/image_upload',
    'CKEditorController@upload')->name('upload');
Route::get('/home',function (){
        return redirect('index');
    }
);
//Route::get('/admin', 'AccountsController@index')->name('admin')->middleware('ad');



Route::get('/index', 'HomeController@index')->name('index');
Route::resource('/tour', 'FrontTourController');
Route::get('/des','HomeController@listDestination')->name('des');
Route::get('/blog',function (){
    return view('blog');
})->name('blog');
Route::get('/contact',function (){
    return view('contact');
})->name('contact');
Route::get('/about',function (){
    return view('about');
})->name('about');
Route::get('/service',function (){
    return view('service');
})->name('service');
Route::get('mail/send', 'MailController@send');
Route::match(['get', 'post'], '/logout', 'Auth\LoginController@logout')->name('logout');



Route::get('/addT',function(){
    $lsDes = Destination::all();
    $lsCat = Category::all();
    return view('admin/tour/add') -> with(['lsDes' => $lsDes, 'lsCat' => $lsCat]);
});
Route::post('/addT','Tourcontroller@save')->name('addT');



Route::group(['middleware'=>'auth'],function (){
    Route::get('/info/{id}', 'HomeController@userInfo')->name('info');
    Route::post('/booktour/accept','BooktourController@booked');
    Route::get('/booktour/{id}','BookTourController@showData')->name('booktour');
    Route::post('/payment/{id}/{time}','BookTourController@create');
    Route::get('/return-vnpay/{id}/{time}','BookTourController@return');
});
Route::group(['middleware'=>'ad'],function(){
    Route::resource('destination', 'DestinationController');
    Route::post('/update-des/{id}','DestinationController@update')->name('destination.update');
    Route::get('/destination_detail/{id}','HomeController@detailDes')->name('destination_detail');
    Route::resource('admin_tour', 'TourController');
    Route::get('/admin', 'AccountsController@index')->name('admin');
    Route::get('delete/{id}','AccountsController@destroy')->name('delete');
    Route::get('active/{id}','AccountsController@active')->name('active');
    Route::get('/searchUser','AccountsController@search')->name('search');
});

app/Tour.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tour extends Model
{
    protected $table = 'tours';
    use SoftDeletes;
    protected $date = ['deleted_at'];
    public function category() {
        return $this->belongsTo('\App\Category');
    }
    public function destination() {
        return $this->belongsTo('\App\Destination');
    }
}

app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Tour;
use App\Destination;
use App\Category;
use Illuminate\Support\Facades\DB;

class TourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $search_title = $request->search_title;

        if(isset($search_title)) {
            $lsTour =
                Tour::where('status','=',1)
                ->where('title', 'like', "%$search_title%")
                    ->paginate(10);
        } else {
            $lsTour = Tour::where('status','=',1)->paginate(10);
        }

        return view("admin.tour.list_tour")
            ->with(['lsTour'=> $lsTour, 'search_title' => $search_title]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $lsDes = Destination::all();
        $lsCat = Category::all();
        return view('admin/tour/add') -> with(['lsDes' => $lsDes, 'lsCat' => $lsCat]);
    }


    public function store(Request $request)
    {
        $msg = [
            'required' => 'trường :attribute bắt buộc nhập',
            'max'      => 'trường :attribute có độ dài nhỏ hơn :max',
        ];
        $this->validate(
            $request,
            [

            ],$msg
        );
        $tour = new Tour();
        $tour->destination_id = $request->destination;
        $tour->tour_name = $request->tour_name;
        $tour->start_at = $request->start_at;
        $tour->category_id = $request->category;
        $tour->price = $request->price;
        $tour->num_of_per = $request->num_of_per;
        $tour->num_of_day = $request->num_of_day;
        $tour->status = $request->status;
        $tour->discount = $request->discount;
        $tour->description = $request->description;
        $tour->vehicle = $request->vehicle;
        $tour->schedule = $request->schedule;
        $tour->time_start = $request->time_start;
//        if($request->hasFile('cover')) {
//            $name = time() . "." . $request->cover->extension();
//            $request->cover->move(public_path('images_upload'), $name);
//            $cover_path = "images_upload/" . $name;
//            $tour->cover = $cover_path;
//        }
        $tour->cover=$request->imageUrl;

            $tour->save();
        $request->session()->flash('success', 'Tour was successful!');
        return redirect()->route("admin_tour.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tour=Tour::find($id);
        return view('detail_tour')->with(['tour'=>$tour]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tour=Tour::find($id);
        $lsDes = Destination::all();
        $lsCat = Category::all();
        return view('admin/tour/edit')->with(['tour'=>$tour,'lsDes' => $lsDes, 'lsCat' => $lsCat]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $tour=Tour::find($id);
        $tour->destination_id = $request->destination;
        $tour->tour_name = $request->tour_name;
        $tour->start_at = $request->start_at;
        $tour->category_id = $request->category;
        $tour->price = $request->price;
        $tour->num_of_per = $request->num_of_per;
        $tour->num_of_day = $request->num_of_day;
        $tour->status = $request->status;
        $tour->discount = $request->discount;
        $tour->description = $request->description;
        $tour->vehicle = $request->vehicle;
        $tour->schedule = $request->schedule;
        $tour->time_start = $request->time_start;
        $tour->cover=$request->imageUrl;
        $tour->save();
        $request->session()->flash('success', 'Update tour was successful!');
        return redirect()->route('admin_tour.index');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $post = Post::find($id);
        $post->delete();
        $request->session()->flash('success', 'Post was deleted!');
        return redirect()->route("post.index");

    }

    public function search(Request $request){
        $name=$request->input('tour');
        $numPeo=$request->input('numPeo');

        $lsTour=Tour::where('status','=',1)
        ->where('tour_name','like','%'.$name.'%')
            ->where('num_of_per','>=',$numPeo)->paginate(8);

        return view("tour")
            ->with(['lsTour'=> $lsTour,'name'=>$name,'num'=>$numPeo]);
    }

    public function save(Request $request){
        $tour=new Tour();
        $tour->destination_id = $request->destination;
        $tour->tour_name = $request->tour_name;
        $tour->start_at = $request->start_at;
        $tour->category_id = $request->category;
        $tour->price = $request->price;
        $tour->num_of_per = $request->num_of_per;
        $tour->num_of_day = $request->num_of_day;
        $tour->status = $request->status;
        $tour->discount = $request->discount;
        $tour->description = $request->description;
        $tour->vehicle = $request->vehicle;
        $tour->schedule = $request->schedule;
        $tour->time_start = $request->time_start;
        $tour->cover=$request->imageUrl;
        $tour->save();
        $request->session()->flash('success', 'Create tour was successful!');
        return redirect()->route("admin_tour.index");
    }



}

resources/views/admin/tour/add.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Add new Tour</h2>
        <form class="form" method="post"
              action="{{asset('addT')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
{{--                <label for="name">Cover</label>--}}
{{--                <input type="file" class="form-control" name="cover">--}}
                <div class="form-group inf container">
                    <input class="btn btn-outline-info btn-sm" type="file" class="form-control" name="image">
                    <img src="" alt="" id="image-preview" style="width: 100px">
                    <input type="hidden" name="imageUrl"  >
                </div>
                <br>
                <label for="status">Destination</label>
                <select class="form-control" name="destination">
                    @foreach($lsDes as $Des)
                        <option value="{{$Des->id}}">{{$Des->name}}</option>
                    @endforeach
                    <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Tour name</label>
                <input type="text" class="form-control" name="tour_name" required="true">
                <br>
                <label for="usr">Start at</label>
                <input type="text" class="form-control" name="start_at"  required="true">
                <br>
                <label for="Category">Category</label>
                <select class="form-control" name="category">
                    @foreach($lsCat as $Cat)
                        <option value="{{$Cat->id}}">{{$Cat->name}}</option>
                    @endforeach
                    <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Price</label>
                <input type="number" class="form-control" name="price"  required="true">
                <br>
                <label for="usr">Number person</label>
                <input type="number" class="form-control" name="num_of_per"  required="true">
                <br>
                <label for="usr">Number of day</label>
                <input type="number" class="form-control" name="num_of_day"  required="true">
                <br>
                <label for="status">Status</label>
                <select class="form-control" name="status">
                    <option value="1">Public</option>
                    <option value="0">Draft</option>
                </select>
                <br>
                <label for="usr">Discount</label>
                <input type="number" class="form-control" name="discount"  required="true">
                <br>
                <label for="usr">Description</label>
                <br>
                <textarea class="form-control" name="description" id="description"  cols="680"  rows="15"></textarea>
                <br>
                <label for="usr">Vehicle</label>
                <input type="text" class="form-control" name="vehicle"  required="true">
                <br>
                <label for="usr">Schedule</label>
                <input type="text" class="form-control" name="schedule"  required="true">
                <br>
                <label for="usr">Time start</label>
                <input type="datetime-local" class="form-control" name="time_start"  required="true">
            </div>
            <input type="submit" value="Add" />
        </form>
    </div>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace( 'description',
            {filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
                filebrowserUploadMethod: 'form'} );
    </script>
    <script>
        
        var cloudName= "a123abc";
        var unsignedUploadPreset="qbhmhxzq";
        var img = document.querySelector('[name="image"]');
        img.onchange = function () {
            var file = this.files[0];
            var url = `https://api.cloudinary.com/v1_1/${cloudName}/upload`;
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    var responseDataJson = JSON.parse(this.responseText);
                    console.log(responseDataJson);
                    var imageUrl = document.querySelector('input[name="imageUrl"]');
                    imageUrl.value = responseDataJson.public_id;
                    document.getElementById('image-preview').src = responseDataJson.url;
                }
            }
            xhr.open('POST', url, true);
            var fd = new FormData();
            fd.append('upload_preset', unsignedUploadPreset);
            fd.append('tags', 'browser_upload');
            fd.append('file', file);
            xhr.send(fd);
        }
        var e = document.getElementById("ddlViewBy");
        var strUser = e.options[e.selectedIndex].text;
    </script>
@endsection

resources/views/admin/tour/add_tour.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Add new Tour</h2>
        <form class="form" method="post"
              action="{{asset('admin_tour')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name">Cover</label>
                <input type="file" class="form-control" name="cover">
                <br>
                <label for="status">Destination</label>
                <select class="form-control" name="destination">
                    @foreach($lsDes as $Des)
                    <option value="{{$Des->id}}">{{$Des->name}}</option>
                        @endforeach
                        <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Tour name</label>
                <input type="text" class="form-control" name="tour_name" required="true">
                <br>
                <label for="usr">Start at</label>
                <input type="text" class="form-control" name="start_at"  required="true">
                <br>
                <label for="Category">Category</label>
                <select class="form-control" name="category">
                    @foreach($lsCat as $Cat)
                    <option value="{{$Cat->id}}">{{$Cat->name}}</option>
                        @endforeach
                        <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Price</label>
                <input type="number" class="form-control" name="price"  required="true">
                <br>
                <label for="usr">Number person</label>
                <input type="number" class="form-control" name="num_of_per"  required="true">
                <br>
                <label for="usr">Number of day</label>
                <input type="number" class="form-control" name="num_of_day"  required="true">
                <br>
                <label for="status">Status</label>
                <select class="form-control" name="status">
                    <option value="1">Public</option>
                    <option value="0">Draft</option>
                </select>
                <br>
                <label for="usr">Discount</label>
                <input type="number" class="form-control" name="discount"  required="true">
                <br>
                <label for="usr">Description</label>
                <br>
                <textarea class="form-control" name="description" id="description"  cols="680"  rows="15"></textarea>
                <br>
                <label for="usr">Vehicle</label>
                <input type="text" class="form-control" name="vehicle"  required="true">
                <br>
                <label for="usr">Schedule</label>
                <input type="text" class="form-control" name="schedule"  required="true">
                <br>
                <label for="usr">Time start</label>
                <input type="datetime-local" class="form-control" name="time_start"  required="true">
            </div>
            <input type="submit" value="Add" />
        </form>
    </div>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace( 'description',
            {filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
                filebrowserUploadMethod: 'form'} );
    </script>
    @endsection

resources/views/admin/tour/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Add new Tour</h2>
        <form class="form" method="post"
              action="{{route('admin_tour.update', $tour->id)}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
{{--                <label for="name">Cover</label>--}}
{{--                <input type="file" class="form-control" name="cover">--}}
                <div class="form-group inf container">
                    <input class="btn btn-outline-info btn-sm" type="file" class="form-control" name="image">
                    <img src="http://res.cloudinary.com/a123abc/image/upload/{{$tour->cover}}" alt="" id="image-preview" style="width: 100px">
                    <input type="hidden" name="imageUrl" value="{{$tour->cover}}" >
                </div>
                <br>
                <label for="status">Destination</label>
                <select class="form-control" name="destination">
                    @foreach($lsDes as $Des)
                        @if($Des->id==$tour->destination_id)
                            <option value="{{$Des->id}}" selected>{{$Des->name}}</option>
                        @else
                            <option value="{{$Des->id}}">{{$Des->name}}</option>
                        @endif
                    @endforeach
                    <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Tour name</label>
                <input type="text" class="form-control" name="tour_name" required="true" value="{{$tour->tour_name}}">
                <br>
                <label for="usr">Start at</label>
                <input type="text" class="form-control" name="start_at"  required="true" value="{{$tour->start_at}}">
                <br>
                <label for="Category">Category</label>
                <select class="form-control" name="category">
                    @foreach($lsCat as $Cat)
                        @if($Cat->id==$tour->category_id)
                            <option value="{{$Cat->id}}" selected>{{$Cat->name}}</option>
                        @else
                            <option value="{{$Cat->id}}">{{$Cat->name}}</option>
                        @endif
                    @endforeach
                    <option value="0">UnKnown</option>
                </select>
                <br>
                <label for="usr">Price</label>
                <input type="number" class="form-control" name="price"  required="true" value="{{$tour->price}}">
                <br>
                <label for="usr">Number person</label>
                <input type="number" class="form-control" name="num_of_per"  required="true" value="{{$tour->num_of_per}}">
                <br>
                <label for="usr">Number of day</label>
                <input type="number" class="form-control" name="num_of_day"  required="true" value="{{$tour->num_of_day}}">
                <input type="hidden" name="status" value="{{$tour->status}}">
                <br>
                <label for="usr">Description</label>
                <br>
                <textarea class="form-control" name="description" id="description"  cols="680"  rows="15"></textarea>
                <input type="hidden"  value="{{$tour->description}}" name="des">
                <br>
                <label for="usr">Vehicle</label>
                <input type="text" class="form-control" name="vehicle"  required="true" value="{{$tour->vehicle}}">
                <br>
                <label for="usr">Time start :{{$tour->time_start}}</label>
                <input type="datetime-local" class="form-control" name="time_start"  required="true" >
            </div>
            <input type="submit" value="Add" />
        </form>
    </div>
    <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace( 'description',
            {filebrowserUploadUrl: "{{route('upload', ['_token' => csrf_token() ])}}",
                filebrowserUploadMethod: 'form'} );
    </script>
    <script>

        var cloudName= "a123abc";
        var unsignedUploadPreset="qbhmhxzq";
        var img = document.querySelector('[name="image"]');
        img.onchange = function () {
            var file = this.files[0];
            var url = `https://api.cloudinary.com/v1_1/${cloudName}/upload`;
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    var responseDataJson = JSON.parse(this.responseText);
                    console.log(responseDataJson);
                    var imageUrl = document.querySelector('input[name="imageUrl"]');
                    imageUrl.value = responseDataJson.public_id;
                    document.getElementById('image-preview').src = responseDataJson.url;
                }
            }
            xhr.open('POST', url, true);
            var fd = new FormData();
            fd.append('upload_preset', unsignedUploadPreset);
            fd.append('tags', 'browser_upload');
            fd.append('file', file);
            xhr.send(fd);
        }
        var e = document.getElementById("ddlViewBy");
        var strUser = e.options[e.selectedIndex].text;
    </script>
@endsection

resources/views/admin/tour/list_tour.blade.php
@extends("header")
@section("container")


    <div class="container">
        <a href="{{route('admin_tour.create')}}">New Tour</a>

        <form method="GET" action="{{route('admin_tour.index')}}">
            @csrf
            <div class="form-group">
                <label for="name">Search</label>
                <input type="text" class="form-control" name="search_title"
                       value="{{$search_title}}">
                <input type="Submit" value="Search" class="btn btn-info my-3" />
            </div>
        </form>

        <table class="table">
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Cover</th>
                <th>Time</th>
                <th>Destination</th>
                <th>View</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
            @foreach($lsTour as $i => $tour)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{$tour->tour_name}}</td>
                    <td><img style="width:100px;" src="http://res.cloudinary.com/a123abc/image/upload/{{$tour->cover}}" /></td>
                    <td>{{$tour->time_start}}</td>
                    <td>{{$tour->destination->name}}</td>
                    <td><a href="{{route('admin_tour.show', $tour->id)}}">View</a></td>
                    <td><a href="{{route('admin_tour.edit', $tour->id)}}">update</a></td>
                    <td>
                        <form action="{{route('admin_tour.destroy', $tour->id)}}"
                              method="POST"
                              onsubmit="return confirm('Sure ?')">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE" />
                            <input type="submit" class="btn btn-sm btn-danger" value="Delete" />
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>

        {{ $lsTour->links() }}
    </div>




@endsection